from datetime import datetime


# Keywords that trigger a full printable report response
REPORT_KEYWORDS = [
    "report", "summary report", "give report", "print report",
    "printable", "full report", "detailed report", "generate report",
    "export report", "1 page", "one page"
]


def is_report_request(query: str) -> bool:
    """Returns True if the user's query is asking for a printable report."""
    q = query.lower()
    return any(kw in q for kw in REPORT_KEYWORDS)


class SalesPrompts:

    @staticmethod
    def _today() -> str:
        return datetime.today().strftime("%d/%m/%Y (%A)")

    @staticmethod
    def followup_message(enquiry_data: dict, similar_docs: list) -> str:
        context = "\n".join(similar_docs)
        return f"""
You are a professional, friendly car sales executive.

Past similar enquiries:
{context}

Current customer enquiry:
Customer: {enquiry_data.get('Customer Name', 'Customer')}
Vehicle: {enquiry_data.get('Vehicle Name / Model', enquiry_data.get('Vehicle Model', 'Unknown'))}
Budget/Payment: {enquiry_data.get('Payment Type', enquiry_data.get('Budget', 'N/A'))}
Source: {enquiry_data.get('Enquiry Source', 'Unknown')}
Status: {enquiry_data.get('Status', 'New')}

Write a short, polite and persuasive WhatsApp follow-up message (maximum 3-4 lines).
Be natural and helpful.
"""

    @staticmethod
    def analyze_lead(enquiry_data: dict, similar_docs: list) -> str:
        context = "\n".join(similar_docs)
        return f"""
You are an expert sales analyst.

Past similar leads:
{context}

Current lead:
{enquiry_data}

Analyze this lead and give:
1. Conversion probability (0-100%)
2. Next best action (one short sentence)
3. Key strengths and risks

Answer in clear bullet points.
"""

    @staticmethod
    def summarize_feedback(feedback_text: str, similar_docs: list) -> str:
        context = "\n".join(similar_docs)
        return f"""
You are a customer feedback expert.

Similar past feedback:
{context}

Current feedback:
"{feedback_text}"

Give:
- Short summary (1-2 sentences)
- Sentiment (Positive / Neutral / Negative)
- One suggestion for the sales team
"""

    @staticmethod
    def general_chat(query: str, context: str) -> str:
        """Normal conversational answer — 2 to 4 sentences, no headers, no bullet points."""
        today = SalesPrompts._today()
        return f"""
You are a Sales CRM Assistant for a vehicle dealership.
Today's date is {today}.

RELEVANT DATA FROM THE CRM DATABASE:
---
{context}
---

User's Question: {query}

STRICT INSTRUCTIONS:
1. Answer ONLY based on the CRM data provided above.
2. Keep your answer SHORT — 2 to 4 sentences only. No bullet points. No headers.
3. If the data is not available, say clearly: "I don't have that information in the CRM database."
4. NEVER answer general knowledge questions or anything unrelated to this dealership's sales data.
5. If out of scope, say: "I can only assist with questions related to this dealership's CRM — enquiries, appointments, and customer feedback."
6. Use today's date ({today}) for any time-relative queries.
7. Be concise and professional.
"""

    @staticmethod
    def report_chat(query: str, context: str) -> str:
        """
        Printable 1-page report format.
        Triggered when the user asks for a 'report'.
        """
        today = SalesPrompts._today()
        return f"""
You are a Sales CRM Assistant for a vehicle dealership.
Today's date is {today}.

RELEVANT DATA FROM THE CRM DATABASE:
---
{context}
---

User's Request: {query}

Generate a clean, professional, printable 1-page sales report based on the data above.

FORMAT RULES (follow exactly):
- Start with a bold title: "SALES CRM REPORT"
- Next line: "Date: {today}"
- Next line: "Generated by: Sales CRM AI Assistant"
- Then a divider line: "─────────────────────────────────────────────"
- Use clear SECTION HEADERS in CAPS (e.g., ENQUIRY SUMMARY, APPOINTMENT SUMMARY, FEEDBACK SUMMARY, KEY INSIGHTS)
- Under each section, use short bullet points with actual data
- End with a "RECOMMENDATIONS" section — 2 to 3 bullet points
- Final line: "─────────────────────────────────────────────"
- Keep total length to fit on ONE printed A4 page
- No unnecessary filler text. Only real data from the context above.
- If some data is missing, skip that section entirely.
"""