# Generated by Django 6.0.3 on 2026-04-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('enquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_record', to='sales.enquiry')),
            ],
            options={
                'db_table': 'sales_customer',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=140, null=True)),
                ('owner', models.CharField(blank=True, max_length=140, null=True)),
                ('docstatus', models.IntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('appoinment_time', models.TimeField(blank=True, null=True)),
                ('appoinment_cancelpost_poned', models.IntegerField(default=0)),
                ('appointment_cancel_reason', models.TextField(blank=True, null=True)),
                ('name1', models.CharField(blank=True, max_length=140, null=True)),
                ('gender', models.CharField(blank=True, max_length=140, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('vehicle_name', models.CharField(blank=True, max_length=140, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('appoinment_date', models.DateField(blank=True, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=140, null=True)),
                ('amended_from', models.CharField(blank=True, max_length=140, null=True)),
                ('naming_series', models.CharField(blank=True, max_length=140, null=True)),
                ('dupicate_data', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, db_column='_user_tags', null=True)),
                ('_comments', models.TextField(blank=True, db_column='_comments', null=True)),
                ('_assign', models.TextField(blank=True, db_column='_assign', null=True)),
                ('_liked_by', models.TextField(blank=True, db_column='_liked_by', null=True)),
                ('sales_enquiry_id', models.ForeignKey(blank=True, db_column='sales_enquiry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.enquiry')),
            ],
            options={
                'db_table': 'sales_appointment',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=140, null=True)),
                ('owner', models.CharField(blank=True, max_length=140, null=True)),
                ('docstatus', models.IntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('feed_back_created_date', models.DateField(blank=True, null=True)),
                ('vehicle_name', models.CharField(blank=True, max_length=140, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=140, null=True)),
                ('customer', models.CharField(blank=True, max_length=140, null=True)),
                ('feed_back_date', models.DateField(blank=True, null=True)),
                ('naming_series', models.CharField(blank=True, max_length=140, null=True)),
                ('amended_from', models.CharField(blank=True, max_length=140, null=True)),
                ('_user_tags', models.TextField(blank=True, db_column='_user_tags', null=True)),
                ('_comments', models.TextField(blank=True, db_column='_comments', null=True)),
                ('_assign', models.TextField(blank=True, db_column='_assign', null=True)),
                ('_liked_by', models.TextField(blank=True, db_column='_liked_by', null=True)),
                ('sales_appoinment_id', models.ForeignKey(blank=True, db_column='sales_appoinment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.appointment')),
                ('sales_enquiry_id', models.ForeignKey(blank=True, db_column='sales_enquiry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.enquiry')),
            ],
            options={
                'db_table': 'sales_feedback',
            },
        ),
    ]
