# Generated by Django 6.0.3 on 2026-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=20, unique=True)),
                ('enquiry_id', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
