# Generated by Django 6.0.3 on 2026-05-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enquiry',
            table=None,
        ),
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
