# Generated by Django 6.0.3 on 2026-05-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_profile'),
        ('sales', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
