from django.db import models

class Enquiry(models.Model):
    name = models.CharField(max_length=140, primary_key=True)
    creation = models.DateTimeField(null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)
    modified_by = models.CharField(max_length=140, null=True, blank=True)
    owner = models.CharField(max_length=140, null=True, blank=True)
    docstatus = models.IntegerField(default=0)
    idx = models.IntegerField(default=0)
    _user_tags = models.TextField(null=True, blank=True, db_column='_user_tags')
    _comments = models.TextField(null=True, blank=True, db_column='_comments')
    _assign = models.TextField(null=True, blank=True, db_column='_assign')
    _liked_by = models.TextField(null=True, blank=True, db_column='_liked_by')
    date = models.DateField(null=True, blank=True)
    customer_enquiry_date = models.DateField(null=True, blank=True)
    phone_no = models.CharField(max_length=10, null=True, blank=True)
    whatsapp_no = models.CharField(max_length=10, null=True, blank=True)
    name1 = models.CharField(max_length=140, null=True, blank=True)
    gender = models.CharField(max_length=140, null=True, blank=True)
    vehicle_name = models.CharField(max_length=140, null=True, blank=True)
    appoinment_date = models.DateField(null=True, blank=True)
    sales_enquiry_status = models.CharField(max_length=140, null=True, blank=True)
    address_1 = models.CharField(max_length=140, null=True, blank=True)
    address_4 = models.CharField(max_length=140, null=True, blank=True)
    state = models.CharField(max_length=140, null=True, blank=True)
    address_2 = models.CharField(max_length=140, null=True, blank=True)
    city = models.CharField(max_length=140, null=True, blank=True)
    pincode = models.CharField(max_length=140, null=True, blank=True)
    address_3 = models.CharField(max_length=140, null=True, blank=True)
    district = models.CharField(max_length=140, null=True, blank=True)
    enquiry_status = models.IntegerField(default=0)
    naming_series = models.CharField(max_length=140, null=True, blank=True)
    amended_from = models.CharField(max_length=140, null=True, blank=True)
    form_closed = models.IntegerField(default=0)
    enquiry_type = models.CharField(max_length=140, null=True, blank=True)
    enquiry_source = models.CharField(max_length=140, null=True, blank=True)
    source_of_information = models.CharField(max_length=140, null=True, blank=True)
    model_name = models.CharField(max_length=140, null=True, blank=True)
    model_code = models.CharField(max_length=140, null=True, blank=True)
    customer_type = models.CharField(max_length=140, null=True, blank=True)
    payment_type = models.CharField(max_length=140, null=True, blank=True)
    test_ride_taken = models.CharField(max_length=140, null=True, blank=True)
    customer_interested_in_exchange = models.CharField(max_length=140, null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)
    email_address = models.CharField(max_length=10, null=True, blank=True)
    down_payment = models.DecimalField(max_digits=21, decimal_places=9, default=0.0)
    emi = models.DecimalField(max_digits=21, decimal_places=9, default=0.0)
    tenure = models.DecimalField(max_digits=21, decimal_places=9, default=0.0)
    which_finance = models.CharField(max_length=140, null=True, blank=True)
    exchange_type = models.CharField(max_length=140, null=True, blank=True)
    vehicle_model_and_make = models.CharField(max_length=140, null=True, blank=True)
    year_of_manufacturing = models.CharField(max_length=140, null=True, blank=True)
    owner_type = models.CharField(max_length=140, null=True, blank=True)
    valid_insurance = models.CharField(max_length=140, null=True, blank=True)
    original_rc_available = models.CharField(max_length=140, null=True, blank=True)
    customer_expected_exchange_price = models.DecimalField(max_digits=21, decimal_places=9, default=0.0)
    price_offer_by_dealer = models.DecimalField(max_digits=21, decimal_places=9, default=0.0)

    class Meta:
        db_table = 'sales_enquiry'

class Customer(models.Model):
    name = models.CharField(max_length=140)
    phone_no = models.CharField(max_length=10)
    email = models.CharField(max_length=140)
    address = models.TextField()
    enquiry = models.OneToOneField(Enquiry, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        db_table = 'sales_customer'

class Appointment(models.Model):
    name = models.CharField(max_length=140, primary_key=True)
    creation = models.DateTimeField(null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)
    modified_by = models.CharField(max_length=140, null=True, blank=True)
    owner = models.CharField(max_length=140, null=True, blank=True)
    docstatus = models.IntegerField(default=0)
    idx = models.IntegerField(default=0)
    date = models.DateField(null=True, blank=True)
    sales_enquiry_id = models.ForeignKey(Enquiry, on_delete=models.SET_NULL, null=True, blank=True, db_column='sales_enquiry_id')
    appoinment_time = models.TimeField(null=True, blank=True)
    appoinment_cancelpost_poned = models.IntegerField(default=0)
    appointment_cancel_reason = models.TextField(null=True, blank=True)
    name1 = models.CharField(max_length=140, null=True, blank=True)
    gender = models.CharField(max_length=140, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    vehicle_name = models.CharField(max_length=140, null=True, blank=True)
    phone_no = models.CharField(max_length=10, null=True, blank=True)
    appoinment_date = models.DateField(null=True, blank=True)
    whatsapp_no = models.CharField(max_length=140, null=True, blank=True)
    amended_from = models.CharField(max_length=140, null=True, blank=True)
    naming_series = models.CharField(max_length=140, null=True, blank=True)
    dupicate_data = models.IntegerField(default=0)
    _user_tags = models.TextField(null=True, blank=True, db_column='_user_tags')
    _comments = models.TextField(null=True, blank=True, db_column='_comments')
    _assign = models.TextField(null=True, blank=True, db_column='_assign')
    _liked_by = models.TextField(null=True, blank=True, db_column='_liked_by')

    class Meta:
        db_table = 'sales_appointment'

class Feedback(models.Model):
    name = models.CharField(max_length=140, primary_key=True)
    creation = models.DateTimeField(null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)
    modified_by = models.CharField(max_length=140, null=True, blank=True)
    owner = models.CharField(max_length=140, null=True, blank=True)
    docstatus = models.IntegerField(default=0)
    idx = models.IntegerField(default=0)
    sales_enquiry_id = models.ForeignKey(Enquiry, on_delete=models.SET_NULL, null=True, blank=True, db_column='sales_enquiry_id')
    feed_back_created_date = models.DateField(null=True, blank=True)
    vehicle_name = models.CharField(max_length=140, null=True, blank=True)
    phone_no = models.CharField(max_length=140, null=True, blank=True)
    customer = models.CharField(max_length=140, null=True, blank=True)
    sales_appoinment_id = models.ForeignKey(Appointment, on_delete=models.SET_NULL, null=True, blank=True, db_column='sales_appoinment_id')
    feed_back_date = models.DateField(null=True, blank=True)
    naming_series = models.CharField(max_length=140, null=True, blank=True)
    amended_from = models.CharField(max_length=140, null=True, blank=True)
    _user_tags = models.TextField(null=True, blank=True, db_column='_user_tags')
    _comments = models.TextField(null=True, blank=True, db_column='_comments')
    _assign = models.TextField(null=True, blank=True, db_column='_assign')
    _liked_by = models.TextField(null=True, blank=True, db_column='_liked_by')

    class Meta:
        db_table = 'sales_feedback'
